[package]
name = "binary"
description = "Defines a specification and trait for external binaries"
version = "0.0.0"
edition = "2021"

[features]
download = ["reqwest", "url"]
download-zip = ["download", "zip"]
download-tar = ["download", "tar"]
download-tar-gz = ["download-tar", "flate2"]
download-tar-xz = ["download-tar", "xz2"]

[dependencies]
async-trait = "0.1.51"
defaults = "0.2.0"
dirs = "4.0.0"
eyre = "0.6.5"
glob = "0.3.0"
once_cell = "1.9.0"
regex = "1.5.4"
semver = "1.0.4"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.13.0", features = ["process", "macros"] }
tracing = "0.1.29"
which = "4.2.2"

flate2 = { version = "1.0.22", optional = true }
reqwest = { version = "0.11.6", optional = true }
tar = { version = "0.4.37", optional = true }
url = { version = "2.2.2", optional = true }
xz2 = { version = "0.1.6", optional = true }
zip = { version = "0.5.13", optional = true }
