[package]
name = "assistant"
version = "0.0.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
codecs = { path = "../codecs" }
common = { path = "../common" }
fastembed = "3.1.1"
format = { path = "../format" }
merge = "0.1.0"
node-authorship = { path = "../node-authorship" }
schema = { path = "../schema" }
secrets = { path = "../secrets" }
serde = { version = "1.0.197", features = ["derive"] }
