[package]
name = "cli-utils"
version = "0.0.0"
edition = "2021"

[dependencies]
comfy-table = "7.1.3"
common = { path = "../common" }
format = { path = "../format" }
is-terminal = { workspace = true }
rpassword = "7.3"
syntect = "5.2.0"
