[package]
name = "cli-utils"
description = "Utilities for command line interfaces"
version = "0.0.0"
edition = "2021"

[features]
default = []
pretty = ["atty", "once_cell", "syntect", "serde_yaml", "termimad", "urlencoding"]
progress = ["events", "linya", "once_cell"]
interact = ["rustyline", "rustyline-derive", "tracing"]

[dependencies]
ansi_term = "0.12.1"
async-trait = "0.1.52"
atty = { version = "0.2.14", optional = true }
color-eyre = "0.6.0"
eyre = "0.6.6"
events = { path = "../events", version = "0.0.0", optional = true }
linya = { version = "0.2.1", optional = true }
once_cell = { version = "1.9.0", optional = true }
regex = "1.5.4"
rustyline = { version = "9.0.0", optional = true }
rustyline-derive = { version = "0.6.0", optional = true }
serde = "1.0.130"
serde_json = "1.0.75"
serde_yaml = { version = "0.8.23", optional = true }
structopt = { version = "0.3.25", features = ["wrap_help"] }
syntect = { version = "4.6.0", optional = true }
termimad = { version = "0.20.0", optional = true }
tracing = { version = "0.1.29", optional = true }
urlencoding = { version = "2.1.0", optional = true }
