[package]
name = "stencila-cli-utils"
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
color-print = "0.3"
comfy-table = "7.2.1"
derive_more = { workspace = true }
eyre = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
stencila-format = { path = "../format" }
stencila-schema = { path = "../schema" }
syntect = "5.3.0"
terminal_size = "0.4.3"
textwrap = { workspace = true }
toml = { workspace = true }
unicode-width = "0.2.2"
url = { workspace = true }

[lints]
workspace = true
