[package]
name = "stencila-cloud"
version = "0.0.0"
edition = "2024"

[dependencies]
cached = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde_with = { workspace = true }
stencila-config = { path = "../config" }
stencila-dirs = { path = "../dirs" }
stencila-secrets = { "path" = "../secrets" }
stencila-version = { "path" = "../version" }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
urlencoding = "2.1"
webbrowser = { workspace = true }

[lints]
workspace = true
