[package]
name = "codec-jats-trait"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-info = { path = "../codec-info" }
codec-jats-derive = { path = "../codec-jats-derive" }
common = { path = "../common" }
quick-xml = { workspace = true }
