[package]
name = "stencila-cli-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
stencila-cli = { path = "../cli" }
stencila-codecs = { path = "../codecs" }
stencila-schema = { path = "../schema" }
tokio = { workspace = true }

[lints]
workspace = true
