[package]
name = "stencila-codemode"
edition = "2024"
version.workspace = true

[dependencies]
async-trait = { workspace = true }
rquickjs = { version = "0.11.0", features = ["futures", "macro", "parallel", "loader"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
