compact.jats.xml:
  decode:
    strip-types:
      # TODO: Implement encoding and decoding `IfBlock`
      - IfBlock

myst:
  decode:
    skip: true # Not supported

qmd:
  decode:
    skip: true # Not supported
