[package]
name = "models"
version = "0.0.0"
edition = "2021"

[dependencies]
cli-utils = { path = "../cli-utils" }
model = { path = "../model" }
models-anthropic = { path = "../models-anthropic" }
models-google = { path = "../models-google" }
models-mistral = { path = "../models-mistral" }
models-ollama = { path = "../models-ollama" }
models-openai = { path = "../models-openai" }
plugins = { path = "../plugins" }
