[package]
name = "codec-person"
description = "A codec for people's names, honorifics and contact details"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec", version = "0.0.0" }
human_name = "1.0.3"
once_cell = "1.9.0"
regex = "1.5.4"

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
