[package]
name = "stencila-models-openai"
version = "0.0.0"
edition = "2024"

[dependencies]
Inflector = { workspace = true }
async-openai = { version = "0.33.0", features = ["rustls"] }
cached = { workspace = true }
itertools = { workspace = true }
stencila-model = { path = "../model" }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
