[package]
name = "models-openai"
version = "0.0.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
async-openai = { version = "0.23.4", features = ["rustls"] }
cached = { workspace = true }
