[package]
name = "stencila-models3"
edition = "2024"
version.workspace = true

[features]
default = []
cli = ["dep:clap", "dep:eyre", "dep:serde_yaml", "dep:stencila-cli-utils"]
secrets = ["dep:stencila-secrets"]

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, optional = true }
directories = { workspace = true }
eyre = { workspace = true, optional = true }
futures = { workspace = true }
jsonschema = { workspace = true }
keyring = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true, optional = true }
stencila-cli-utils = { path = "../cli-utils", optional = true }
stencila-secrets = { path = "../secrets", optional = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }

[dev-dependencies]

[lints]
workspace = true
