[package]
name = "stencila-models3"
edition = "2024"
version.workspace = true

[features]
default = []
secrets = ["dep:stencila-secrets"]

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
jsonschema = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stencila-secrets = { path = "../secrets", optional = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }

[dev-dependencies]

[lints]
workspace = true
