[package]
name = "stencila-codec-csv"
version = "0.0.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
stencila-codec = { path = "../codec" }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
