[package]
name = "buildpacks"
description = "Buildpacks for building project container images"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils", "structopt", "tokio"]

[dependencies]
buildpack = { path = "../buildpack", version = "0.0.0" }
binary-pack = { path = "../binary-pack", version = "0.0.0" }
once_cell = "1.9.0"
regex = "1.5.4"

cli-utils = { path = "../cli-utils", version = "0.0.0", optional = true, features = ["pretty"] }
structopt = { version = "0.3.25", optional = true }
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros"], optional = true}

buildpack-apt = { path = "../buildpack-apt", version = "0.0.0", optional = true }
buildpack-dockerfile = { path = "../buildpack-dockerfile", version = "0.0.0", optional = true }
buildpack-node = { path = "../buildpack-node", version = "0.0.0", optional = true }
buildpack-python = { path = "../buildpack-python", version = "0.0.0", optional = true }
buildpack-r = { path = "../buildpack-r", version = "0.0.0", optional = true }
buildpack-stencila = { path = "../buildpack-stencila", version = "0.0.0", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
