[package]
name = "node-coerce"
description = "Coerce a JSON value to a Stencila document node"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-date = { path = "../codec-date", version = "0.0.0" }
codec-person = { path = "../codec-person", version = "0.0.0" }
codec = { path = "../codec", version = "0.0.0" }
eyre = "0.6.5"
Inflector = "0.11.4"
once_cell = "1.9.0"
regex = "1.5.4"
serde = "1.0.130"
serde_json = "1.0.75"
stencila-schema = "1.16.1"
tracing = "0.1.29"
utils = { path = "../utils", version = "0.0.0" }

[dev-dependencies]
serde_yaml = "0.8.23"
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
