[package]
name = "stencila-codec-directory"
version = "0.0.0"
edition = "2024"

[dependencies]
ignore = "0.4.25"
mime_guess = { workspace = true }
stencila-codec = { path = "../codec" }

[lints]
workspace = true
