compact.jats.xml:
  decode:
    strip-types:
      # TODO: implement encoding and decoding for `CallBlock`
      - CallBlock

myst:
  decode:
    skip: true # Not supported

pandoc:
  decode:
    strip-props:
      # Not currently supported
      - CallArgument.value

qmd:
  decode:
    skip: true # Not supported
