[package]
name = "stencila-node-url"
version = "0.0.0"
edition = "2024"

[dependencies]
base64 = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stencila-node-id = { path = "../node-id" }
stencila-node-path = { path = "../node-path" }
stencila-node-type = { path = "../node-type" }
strum = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
