[package]
name = "stencila-codec-png"
version = "0.0.0"
edition = "2024"

[dependencies]
stencila-codec = { path = "../codec" }
stencila-codec-dom-trait = { path = "../codec-dom-trait" }
stencila-codec-latex-trait = { path = "../codec-latex-trait" }
stencila-convert = { path = "../convert" }
stencila-images = { path = "../images" }

[lints]
workspace = true
