[package]
name = "graph"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
format = { path = "../format" }
petgraph = { version = "0.7.0", features = ["serde-1"] }
schema = { path = "../schema" }

[lints]
workspace = true
