[package]
name = "codec-html"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-html-trait = { path = "../codec-html-trait" }
minify-html = "0.11.1"
quick-xml = "0.30.0"
