[package]
name = "codec-html"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-html-trait = { path = "../codec-html-trait" }
quick-xml = { workspace = true }
tl = "0.7.8"

[lints]
workspace = true
