[package]
name = "stencila-codec-latex"
version = "0.0.0"
edition = "2024"

[dependencies]
itertools = { workspace = true }
regex = { workspace = true }
stencila-codec = { path = "../codec" }
stencila-codec-latex-trait = { path = "../codec-latex-trait" }
stencila-codec-pandoc = { path = "../codec-pandoc" }
stencila-node-media = { path = "../node-media" }
tokio = { workspace = true }

[dev-dependencies]
glob = { workspace = true }
insta = { workspace = true }
stencila-document = { path = "../document" }
which = { workspace = true }

[lints]
workspace = true
