[package]
name = "codec-latex"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-latex-trait = { path = "../codec-latex-trait" }
codec-pandoc = { path = "../codec-pandoc" }

[dev-dependencies]
common-dev = { path = "../common-dev" }
which = { workspace = true }

[lints]
workspace = true
