[package]
name = "prompt"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-markdown-trait = {path = "../codec-markdown-trait" }
kernel-quickjs = { path = "../kernel-quickjs" }
kernels = { path = "../kernels" }
rquickjs = { version = "0.6.2", features = ["futures", "macro", "parallel"] }

[dev-dependencies]
common-dev = { path = "../common-dev" }

[lints]
workspace = true
