[package]
name = "kernel-style"
version = "0.0.0"
edition = "2021"

[dependencies]
kernel = { path = "../kernel" }
kernel-jinja = { path = "../kernel-jinja" }
railwind = { git = "https://github.com/nokome/railwind", rev = "e804d17b3f1e08ae96ab4aa048d237fc94e39911" }

[dev-dependencies]
common-dev = { path = "../common-dev" }
