[package]
name = "codec-ipynb"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-markdown = { path = "../codec-markdown" }
jupyter-protocol = "0.5.0"
nbformat = "0.9.0"
