[package]
name = "stencila-codec-ipynb"
version = "0.0.0"
edition = "2024"

[dependencies]
jupyter-protocol = "1.0.0"
nbformat = "1.0.0"
serde_json = { workspace = true }
stencila-codec = { path = "../codec" }
stencila-codec-dom = { path = "../codec-dom" }
stencila-codec-markdown = { path = "../codec-markdown" }

[lints]
workspace = true
