[package]
name = "stencila-attractor"
edition = "2024"
version.workspace = true

[dependencies]
chrono = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
