compact.jats.xml:
  decode:
    strip-types:
      # TODO: Implement encoding and decoding `ForBlock`
      - ForBlock

myst:
  decode:
    skip: true # Not supported

pandoc:
  decode:
    strip-props:
      # Not yet supported
      - ForBlock.otherwise

qmd:
  decode:
    skip: true # Not supported
