[package]
name = "stencila-prompts"
version = "0.0.0"
edition = "2024"

[dependencies]
Inflector = { workspace = true }
cached = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rust-embed = { version = "8.7.2", features = ["interpolate-folder-path", "include-exclude"] }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stencila-cli-utils = { path = "../cli-utils" }
stencila-codec-markdown = { path = "../codec-markdown" }
stencila-codecs = { path = "../codecs" }
stencila-dirs = { path = "../dirs" }
stencila-model = { path = "../model" }
stencila-models = { path = "../models" }
stencila-version = { path = "../version" }
tar = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
