[package]
name = "codec-markdown"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-json5-trait = { path = "../codec-json5-trait" }
codec-markdown-trait = { path = "../codec-markdown-trait" }
codec-text-trait = { path = "../codec-text-trait" }
nom = "7.1.3"
pulldown-cmark = "0.9.3"


[dev-dependencies]
common-dev = { path = "../common-dev" }
