[package]
name = "stencila-codec-ghi"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
directories = { workspace = true }
eyre = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
stencila-ask = { path = "../ask" }
stencila-cli-utils = { path = "../cli-utils" }
stencila-cloud = { path = "../cloud" }
stencila-codec = { path = "../codec" }
stencila-codec-docx = { path = "../codec-docx" }
stencila-secrets = { path = "../secrets" }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
webbrowser = { workspace = true }

[lints]
workspace = true
