[package]
name = "codec-json"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
version = { path = "../version" }

[dev-dependencies]
common-dev = { path = "../common-dev" }
