[package]
name = "stencila-codec-json5-trait"
version = "0.0.0"
edition = "2024"

[dependencies]
eyre = { workspace = true }
json5 = "1.3.0"
json5format = "0.2.6"
serde = { workspace = true }

[lints]
workspace = true
