[package]
name = "stencila-publish-ghost"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
jsonwebtoken = { version = "10.2.0", default-features = false, features = ["rust_crypto"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
stencila-cli-utils = { "path" = "../cli-utils" }
stencila-codec-text = { "path" = "../codec-text" }
stencila-document = { path = "../document" }
stencila-node-media = { "path" = "../node-media" }
stencila-remotes = { path = "../remotes" }
stencila-secrets = { "path" = "../secrets" }
strum = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
