[package]
name = "stencila-mcp"
edition = "2024"
version.workspace = true

[dependencies]
async-trait = { workspace = true }
directories = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stencila-config = { path = "../config" }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
