[package]
name = "stencila-codec"
version = "0.0.0"
edition = "2024"

[features]
proptest-min = ["stencila-schema/proptest-min"]
proptest-low = ["stencila-schema/proptest-low"]
proptest-high = ["stencila-schema/proptest-high"]
proptest-max = ["stencila-schema/proptest-max"]

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
smart-default = { workspace = true }
stencila-codec-info = { path = "../codec-info" }
stencila-codec-utils = { path = "../codec-utils" }
stencila-config = { path = "../config" }
stencila-format = { path = "../format" }
stencila-node-strip = { path = "../node-strip" }
stencila-schema = { path = "../schema" }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
