[package]
name = "codec"
description = "Defines a specification and trait for codecs"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
eyre = "0.6.5"
serde = { version = "1.0.130", features = ["derive"] }
stencila-schema = "1.14.0" 
utils = { path = "../utils", version = "0.0.0" }
