[package]
name = "codec"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-losses = { path = "../codec-losses" }
common = { path = "../common" }
format = { path = "../format" }
schema = { path = "../schema" }
status = { path = "../status" }
