[package]
name = "kernel-calc"
description = "A kernel that evaluates simple calculator like numerical expressions"
version = "0.0.0"
edition = "2021"

[dependencies]
kernel = { path = "../kernel", version = "0.0.0" }
fasteval = "0.2.4"
once_cell = "1.8.0"
regex = "1.5.4"

[dev-dependencies]
tokio = { version = "1.13.0", features = ["rt", "macros"] }
test-utils = { path = "../test-utils", version = "0.0.0" }
