compact.jats.xml:
  decode:
    strip-types:
      # TODO: Implement encoding and decoding `StyledBlock`
      - StyledBlock

smd:
  decode:
    strip-props:
      # Not supported in Markdown
      - StyledBlock.style_language

myst:
  decode:
    skip: true # Not supported

qmd:
  decode:
    strip-props:
      - StyledBlock.style_language # Not supported
      - StyledBlock.code # Supported but does not parse double closing braces in one of these examples

pandoc:
  decode:
    strip-props:
      # As for Markdown
      - StyledBlock.style_language
