[package]
name = "codec-html-trait"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-html-derive = { path = "../codec-html-derive" }
common = { path = "../common" }
html-escape = "0.2.13"

[lints]
workspace = true
