[package]
name = "lsp"
version = "0.0.0"
edition = "2021"

[dependencies]
async-lsp = { version = "0.2.1", features = ["tokio"] }
codec-markdown-trait = { path = "../codec-markdown-trait" }
codec-text-trait = { path = "../codec-text-trait" }
codecs = { path = "../codecs" }
common = { path = "../common" }
document = { path = "../document" }
kernels = { path = "../kernels" }
models = { path = "../models" }
node-execute = { path = "../node-execute" }
percent-encoding = "2.3.1"
prompts = { path = "../prompts" }
schema = { path = "../schema" }
tokio-util = { version = "0.7.13", features = ["compat"] }
tower = "0.5.2"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }

[lints]
workspace = true
