[package]
name = "lsp"
version = "0.0.0"
edition = "2021"

[dependencies]
async-lsp = { version = "0.2.0", features = ["tokio"] }
codec-text-trait = { path = "../codec-text-trait" }
codecs = { path = "../codecs" }
common = { path = "../common" }
document = { path = "../document" }
node-execute = { path = "../node-execute" }
prompts = { path = "../prompts" }
schema = { path = "../schema" }
tokio-util = { version = "0.7.10", features = ["compat"] }
tower = "0.5.0"
tracing-subscriber = "0.3.18"
