[package]
name = "stencila-lsp"
version = "0.0.0"
edition = "2024"

[dependencies]
Inflector = { workspace = true }
async-lsp = { version = "0.2.2", features = ["tokio"] }
async-trait = { workspace = true }
chrono = { workspace = true }
eyre = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
percent-encoding = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
smart-default = { workspace = true }
stencila-ask = { path = "../ask" }
stencila-cloud = { path = "../cloud" }
stencila-codec-markdown-trait = { path = "../codec-markdown-trait" }
stencila-codec-text-trait = { path = "../codec-text-trait" }
stencila-codec-utils = { path = "../codec-utils" }
stencila-codecs = { path = "../codecs" }
stencila-dirs = { path = "../dirs" }
stencila-document = { path = "../document" }
stencila-kernels = { path = "../kernels" }
stencila-models = { path = "../models" }
stencila-node-execute = { path = "../node-execute" }
stencila-node-find = { path = "../node-find" }
stencila-prompts = { path = "../prompts" }
stencila-remotes = { path = "../remotes" }
stencila-schema = { path = "../schema" }
tokio = { workspace = true }
tokio-util = { version = "0.7.17", features = ["compat"] }
tower = "0.5.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
