[package]
name = "codec-jats"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-jats-trait = { path = "../codec-jats-trait" }
quick-xml = { workspace = true }
roxmltree = "0.20.0"

[dev-dependencies]
common-dev = { path = "../common-dev" }
