[package]
name = "stencila-node-diagnostics"
version = "0.0.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
eyre = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
stencila-codec-info = { path = "../codec-info" }
stencila-format = { path = "../format" }
stencila-schema = { path = "../schema" }
strum = { workspace = true }

[lints]
workspace = true
