[package]
name = "stencila-python"
version = "0.102.1"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stencila = { path = "../rust" }
pyo3 = { version = "=0.14.1", features = ["extension-module"] }
