[package]
name = "stencila-codec-biblio"
version = "0.0.0"
edition = "2024"

[dependencies]
Inflector = { workspace = true }
cached = { workspace = true }
hayagriva = { version = "0.9.1", features = ["archive"] }
itertools = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
stencila-codec = { path = "../codec" }
stencila-codec-markdown-trait = { path = "../codec-markdown-trait" }
stencila-codec-text-trait = { path = "../codec-text-trait" }
stencila-dirs = { path = "../dirs" }
tracing = { workspace = true }
tokio = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
glob = { workspace = true }
insta = { workspace = true }
pretty_assertions = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
