[package]
name = "document"
version = "0.0.0"
edition = "2021"

[dependencies]
codecs = { path = "../codecs" }
common = { path = "../common" }
format = { path = "../format" }
node-store = { path = "../node-store" }
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
schema = { path = "../schema" }

[dev-dependencies]
common-dev = { path = "../common-dev" }
