[package]
name = "document"
version = "0.0.0"
edition = "2021"

[dependencies]
codecs = { path = "../codecs" }
common = { path = "../common" }
format = { path = "../format" }
node-store = { path = "../node-store" }
notify = { version = "5.1.0", default-features = false, features = ["macos_kqueue"] }
schema = { path = "../schema" }
