[package]
name = "stencila-document"
version = "0.0.0"
edition = "2024"

[dependencies]
Inflector = { workspace = true }
chrono = { workspace = true }
chrono-humanize = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
json-patch = "1.2.0"
notify = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
similar = { workspace = true }
smart-default = { workspace = true }
stencila-ask = { path = "../ask" }
stencila-cli-utils = { path = "../cli-utils" }
stencila-cloud = { path = "../cloud" }
stencila-codec-utils = { path = "../codec-utils" }
stencila-codec-gdoc = { path = "../codec-gdoc" }
stencila-codec-json = { path = "../codec-json" }
stencila-codec-m365 = { path = "../codec-m365" }
stencila-codec-text = { path = "../codec-text" }
stencila-codecs = { path = "../codecs" }
stencila-config = { path = "../config" }
stencila-dirs = { path = "../dirs" }
stencila-format = { path = "../format" }
stencila-kernels = { path = "../kernels" }
stencila-node-canonicalize = { path = "../node-canonicalize" }
stencila-node-db = { path = "../node-db" }
stencila-node-diagnostics = { path = "../node-diagnostics" }
stencila-node-execute = { path = "../node-execute" }
stencila-node-find = { path = "../node-find" }
stencila-node-first = { path = "../node-first" }
stencila-node-map = { path = "../node-map" }
stencila-node-strip = { path = "../node-strip" }
stencila-remotes = { path = "../remotes" }
stencila-schema = { path = "../schema" }
stencila-site = { path = "../site" }
stencila-tools = { path = "../tools" }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
ntest = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
