[package]
name = "document"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-json = { path = "../codec-json" }
codecs = { path = "../codecs" }
common = { path = "../common" }
format = { path = "../format" }
kernels = { path = "../kernels" }
json-patch = "1.2.0"
node-execute = { path = "../node-execute" }
node-find = { path = "../node-find" }
node-map = { path = "../node-map" }
node-strip = { path = "../node-strip" }
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
schema = { path = "../schema" }

[dev-dependencies]
common-dev = { path = "../common-dev" }

[lints]
workspace = true
