[package]
name = "stencila-codec-lexical"
version = "0.0.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
monostate = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
smart-default = { workspace = true }
stencila-codec = { path = "../codec" }
stencila-codec-dom-trait = { path = "../codec-dom-trait" }
stencila-codec-markdown = { path = "../codec-markdown" }
stencila-codec-text = { path = "../codec-text" }
tracing = { workspace = true }

[dev-dependencies]
glob = { workspace = true }
insta = { workspace = true }
regex = { workspace = true }
