[package]
name = "stencila-kernel-quickjs"
version = "0.0.0"
edition = "2024"

[dependencies]
indexmap = { workspace = true }
regex = { workspace = true }
rquickjs = { version = "0.10.0", features = ["futures", "macro", "parallel"] }
serde_json = { workspace = true }
stencila-kernel = { path = "../kernel" }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-log = { workspace = true }

[lints]
workspace = true
