# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "stencila"
version = "0.123.0"
authors = ["Stencila <hello@stenci.la>"]
edition = "2018"

# Compile time feature flags. See https://www.worthe-it.co.za/blog/2018-11-18-compile-time-feature-flags-in-rust.html
# All features are on by default, use `--no-default-features --features="json http ..."` to
# cherry pick certain features.
# Our use of features is somewhat over the top but should hopefully allow us to create more
# minimal binaries as needed (e.g. for creating really small container images).

[features]

cli = ["structopt"]
cli-feedback = ["ansi_term", "color-eyre", "linya"]
cli-pretty = ["atty", "syntect", "termimad"]
cli-view = ["webbrowser"]
cli-interact = ["ansi_term", "rustyline", "rustyline-derive"]

serve = []
serve-stdio = ["serve"]
serve-http = ["serve", "sudo", "warp", "jsonwebtoken", "rust-embed"]
serve-ws = ["serve-http"]

request = []
request-docker = ["bollard"]
request-http = ["reqwest", "jsonwebtoken"]
request-stdio = []
request-ws = ["tokio-tungstenite", "jsonwebtoken"]

binaries = ["flate2", "reqwest", "semver", "tar", "which", "xz2", "zip"]

plugins = ["jsonschema", "semver"]
plugins-binary = ["plugins", "self_update"]
plugins-docker = ["plugins", "bollard"]
plugins-javascript = ["plugins"]
plugins-link = ["plugins"]
plugins-python = ["plugins"]
plugins-r = ["plugins"]

kernels-calc = ["fasteval"]
kernels-jupyter = ["zmq/vendored"]

upgrade = ["self_update"]

import-elife = ["minidom"]
import-github = []

decode-date = ["dtparse"]
decode-docx = ["decode-pandoc"]
decode-html = ["decode-md", "kuchiki", "markup5ever"]
decode-ipynb = [
  "coerce",
  "decode-md",
  "decode-html",
  "decode-txt",
  "strip-ansi-escapes",
]
decode-json = []
decode-json5 = ["coerce"]
decode-latex = ["decode-pandoc"]
decode-md = ["pulldown-cmark", "nom", "coerce", "decode-html"]
decode-pandoc = ["binaries", "pandoc_types"]
decode-person = ["human_name"]
decode-rmd = ["decode-md"]
decode-rpng = ["png"]
decode-toml = []
decode-txt = ["decode-json5"]
decode-yaml = []

encode-docx = ["encode-pandoc"]
encode-ipynb = ["encode-md"]
encode-json = []
encode-json5 = []
encode-latex = ["encode-pandoc"]
encode-md = []
encode-pandoc = ["binaries", "pandoc_types"]
encode-pdf = ["chromiumoxide"]
encode-png = ["chromiumoxide"]
encode-rmd = ["encode-md"]
encode-rpng = ["encode-png", "png"]
encode-toml = []
encode-yaml = []

coerce = ["decode-date", "decode-person"]

reshape = ["decode-date", "decode-person"]

compile-calc = []
compile-js = ["tree-sitter", "tree-sitter-javascript"]
compile-py = ["tree-sitter", "tree-sitter-python"]
compile-r = ["tree-sitter", "tree-sitter-r"]
compile-ts = ["tree-sitter", "tree-sitter-javascript", "tree-sitter-typescript"]

query-jmespath = ["jmespatch"]
query-jsonptr = []

default = [
  "cli",
  "cli-feedback",
  "cli-pretty",
  "cli-view",
  "cli-interact",
  "serve",
  "serve-stdio",
  "serve-http",
  "serve-ws",
  "request",
  "request-docker",
  "request-http",
  "request-stdio",
  "request-ws",
  "binaries",
  "plugins",
  "plugins-binary",
  "plugins-docker",
  "plugins-link",
  "plugins-javascript",
  "plugins-python",
  "plugins-r",
  "kernels-calc",
  "kernels-jupyter",
  "upgrade",
  "import-elife",
  "import-github",
  "decode-date",
  "decode-docx",
  "decode-html",
  "decode-ipynb",
  "decode-json",
  "decode-json5",
  "decode-latex",
  "decode-md",
  "decode-pandoc",
  "decode-person",
  "decode-rmd",
  "decode-rpng",
  "decode-toml",
  "decode-txt",
  "decode-yaml",
  "encode-docx",
  "encode-ipynb",
  "encode-json",
  "encode-json5",
  "encode-latex",
  "encode-md",
  "encode-pandoc",
  "encode-pdf",
  "encode-png",
  "encode-rmd",
  "encode-rpng",
  "encode-toml",
  "encode-yaml",
  "coerce",
  "reshape",
  "compile-calc",
  "compile-js",
  "compile-py",
  "compile-r",
  "compile-ts",
  "query-jsonptr",
  "query-jmespath",
]

[dependencies]
ansi_term = { version = "=0.12.1", optional = true }
async-recursion = "0.3.2"
async-trait = "=0.1.51"
atty = { version = "=0.2.14", optional = true }
base64 = "=0.13.0"
bollard = { version = "=0.11.0", optional = true }
chromiumoxide = { version = "=0.3.1", optional = true, features = [
  "tokio-runtime",
] }
chrono = { version = "=0.4.19", features = ["serde"] }
color-eyre = { version = "=0.5.11", optional = true }
crossbeam-channel = "=0.5.1"
defaults = "=0.2.0"
derivative = "=2.2.0"
derive_more = "0.99.16"
dirs-next = "=2.0.0"
dtparse = { version = "=1.2.0", optional = true }
enum_dispatch = "=0.3.7"
exitcode = "=1.1.2"
eyre = "=0.6.5"
fasteval = { version = "=0.2.4", optional = true }
flate2 = { version = "=1.0.22", optional = true }
futures = "=0.3.17"
gitignore = "=1.0.7"
glob = "=0.3.0"
handlebars = "=4.1.3"
hex = "0.4.3"
hmac = "0.11.0"
html-escape = "=0.2.9"
human_name = { version = "=1.0.2", optional = true }
humantime = "=2.1.0"
ignore = "=0.4.18"
Inflector = "0.11.4"
itertools = "0.10.1"
jmespatch = { version = "=0.3.0", optional = true }
json5 = "=0.4.1"
jsonschema = { version = "=0.12.2", optional = true }
jsonwebtoken = { version = "=7.2.0", optional = true }
kuchiki = { version = "=0.8.1", optional = true }
lexiclean = "=0.0.1"
linya = { version = "=0.2.1", optional = true }
maplit = "=1.0.2"
markup5ever = { version = "=0.10.1", optional = true }
mime_guess = "=2.0.3"
minidom = { version = "=0.13.0", optional = true }
nanoid = "=0.4.0"
nom = { version = "=7.0.0", optional = true }
notify = "=4.0.17"
once_cell = "=1.8.0"
pandoc_types = { version = "=0.4.0", optional = true }
path-slash = "=0.1.4"
pathdiff = "=0.2.1"
petgraph = { version = "=0.6.0", features = ["serde-1"] }
png = { version = "=0.17.2", optional = true }
portpicker = "0.1.1"
pulldown-cmark = { version = "=0.8.0", optional = true }
quick-xml = "=0.22.0"
rand = "=0.8.4"
regex = "=1.5.4"
reqwest = { version = "=0.11.6", optional = true, features = ["json"] }
rust-embed = { version = "=6.2.0", features = ["compression"], optional = true }
rustyline = { version = "=9.0.0", optional = true }
rustyline-derive = { version = "=0.5.0", optional = true }
schemars = { version = "=0.8.6", features = ["preserve_order", "chrono"] }
self_update = { version = "=0.27.0", optional = true, features = [
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate",
] }
semver = { version = "=1.0.4", optional = true }
serde = { version = "=1.0.130", features = ["derive", "rc"] }
serde_json = { version = "=1.0.68", features = ["preserve_order"] }
serde_with = "=1.11.0"
serde_yaml = "=0.8.21"
sha2 = "0.9.8"
similar = { version = "=2.1.0", features = ["unicode"] }
slug = "=0.1.4"
stencila-schema = "=1.12.0"
strip-ansi-escapes = { version = "0.1.1", optional = true }
structopt = { version = "=0.3.25", features = ["wrap_help"], optional = true }
strum = { version = "=0.22.0", features = ["derive"] }
strum_macros = "=0.22.0"
sudo = { version = "=0.6.0", optional = true }
syntect = { version = "=4.6.0", optional = true }
tar = { version = "=0.4.37", optional = true }
tempfile = "3.2.0"
termimad = { version = "=0.16.4", optional = true }
thiserror = "=1.0.30"
tokio = { version = "=1.12.0", features = ["full"] }
tokio-stream = "=0.1.7"
tokio-tungstenite = { version = "=0.15.0", optional = true }
toml = "=0.5.8"
tracing = "=0.1.29"
tracing-appender = "=0.1.2"
tracing-error = "=0.1.2"
tracing-serde = "=0.1.2"
tracing-subscriber = "=0.2.25"
tree-sitter = { version = "=0.19.5", optional = true }
tree-sitter-javascript = { version = "=0.19.0", optional = true }
tree-sitter-python = { version = "=0.19.0", optional = true }
tree-sitter-r = { version = "=0.19.3", optional = true }
tree-sitter-typescript = { version = "=0.19.0", optional = true }
unicode-segmentation = "=1.8.0"
url = "=2.2.2"
urlencoding = "2.1.0"
validator = { version = "=0.14.0", features = ["derive"] }
warp = { version = "=0.3.1", optional = true }
webbrowser = { version = "=0.5.5", optional = true }
which = { version = "=4.2.2", optional = true }
xz2 = { version = "=0.1.6", optional = true }
zip = { version = "=0.5.13", optional = true }
zmq = { version = "=0.9.2", optional = true, default-features = false }

codec-date = { path = "../codec-date", version = "0.0.0" }
codec-json = { path = "../codec-json", version = "0.0.0" }
codec-json5 = { path = "../codec-json5", version = "0.0.0" }
codec-person = { path = "../codec-person", version = "0.0.0" }
codec-toml = { path = "../codec-toml", version = "0.0.0" }
codec-trait = { path = "../codec-trait", version = "0.0.0" }
codec-yaml = { path = "../codec-yaml", version = "0.0.0" }
node-coerce = { path = "../node-coerce", version = "0.0.0" }

[dev-dependencies]
criterion = "0.3.5"
insta = { version = "1.8.0", features = ["glob"] }
pretty_assertions = "1.0.0"
proptest = "1.0.0"

[[bench]]
harness = false
name = "compile_code"
