[package]
name = "common-dev"
version = "0.0.0"
edition = "2021"

[dependencies]
insta = { version = "1.34.0", features = ["json", "redactions"] }
ntest = "0.9.0"
pretty_assertions = "1.4.0"
proptest = "1.4.0"
