[package]
name = "stencila-config"
edition = "2024"
version.workspace = true

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
figment = { version = "0.10.19", features = ["toml"] }
glob = { workspace = true }
indexmap = { workspace = true }
notify = { workspace = true }
regex = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
stencila-ask = { path = "../ask" }
stencila-cli-utils = { path = "../cli-utils" }
stencila-dirs = { path = "../dirs" }
stencila-format = { path = "../format" }
stencila-schema = { path = "../schema" }
strum = { workspace = true }
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }
tokio = { workspace = true }
toml = { workspace = true }
toml_edit = "0.23.9"
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
jsonschema = "0.37.4"
serial_test = "3.2.0"
tempfile = { workspace = true }

[lints]
workspace = true
