[package]
name = "stencila-config"
edition = "2024"
version.workspace = true

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
figment = { version = "0.10.19", features = ["toml"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
stencila-cli-utils = { path = "../cli-utils" }
stencila-dirs = { path = "../dirs" }
stencila-format = { path = "../format" }
strum = { workspace = true }
toml = { workspace = true }
toml_edit = "0.22"
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
serial_test = "3.2.0"
tempfile = { workspace = true }

[lints]
workspace = true
