# TODO: Support the following codec/node type combinations

compact.jats.xml:
  encode:
    strip-types:
      - DeleteBlock
      - DeleteInline
      - InsertBlock
      - InsertInline
      - ReplaceBlock
      - ReplaceInline
  decode:
    strip-types:
      - CallBlock
      - Claim
      - CodeBlock
      - CodeChunk
      - Figure
      - ForBlock
      - IfBlock
      - IncludeBlock
      - List
      - MathBlock
      - StyledBlock
      - Table
smd:
  encode:
    strip-types:
      # TODO: check why this needs to be stripped
      - Figure

myst:
  encode:
    strip-types:
      # As for Markdown
      - Figure
