[package]
name = "kernel-rhai"
version = "0.0.0"
edition = "2021"

[dependencies]
kernel = { path = "../kernel" }
rhai = { version = "1.20.1", features = ["sync", "serde"] }

[dev-dependencies]
common-dev = { path = "../common-dev" }
test-log = { workspace = true }

[lints]
workspace = true
