[package]
name = "kernels"
version = "0.0.0"
edition = "2021"

[dependencies]
cli-utils = { path = "../cli-utils" }
context = { path = "../context" }
kernel = { path = "../kernel" }
kernel-bash = { path = "../kernel-bash" }
kernel-node = { path = "../kernel-node" }
kernel-python = { path = "../kernel-python" }
kernel-r = { path = "../kernel-r" }
kernel-rhai = { path = "../kernel-rhai" }
kernel-tex = { path = "../kernel-tex" }
plugins = { path = "../plugins" }
