[package]
name = "kernels"
version = "0.0.0"
edition = "2021"

[dependencies]
cli-utils = { path = "../cli-utils" }
kernel = { path = "../kernel" }
kernel-asciimath = { path = "../kernel-asciimath" }
kernel-bash = { path = "../kernel-bash" }
kernel-graphviz = { path = "../kernel-graphviz" }
kernel-jinja = { path = "../kernel-jinja" }
kernel-nodejs = { path = "../kernel-nodejs" }
kernel-python = { path = "../kernel-python" }
kernel-quickjs = { path = "../kernel-quickjs" }
kernel-r = { path = "../kernel-r" }
kernel-rhai = { path = "../kernel-rhai" }
kernel-style = { path = "../kernel-style" }
kernel-tex = { path = "../kernel-tex" }
plugins = { path = "../plugins" }

[dev-dependencies]
common-dev = { path = "../common-dev" }
test-log = { version = "0.2.15", default-features = false, features = ["trace"] }
