[package]
edition = "2021"
name = "kernels"
version = "0.0.0"

[features]
default = ["kernel-store", "kernel-micro"]
cli = ["cli-utils", "events", "parsers", "once_cell", "structopt"]

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
derive_more = "0.99.17"
formats = { path = "../formats", version = "0.0.0" }
graph-triples = { path = "../graph-triples", version = "0.0.0" }
humantime = { version = "2.1.0" }
kernel = { path = "../kernel", version = "0.0.0" }
regex = "1.5.4"
serde = "1.0.130"
serde_json = "1.0.72"
slug = "0.1.4"
strum = { version = "=0.23.0", features = ["derive"] }
tokio = { version = "1.13.0", features = ["sync", "time"] }
tracing = "0.1.29"
validator = "0.14.0"

# For `cli` feature
cli-utils = { path = "../cli-utils", version = "0.0.0", optional = true }
events = { path = "../events", version = "0.0.0", optional = true }
once_cell = { version = "1.8.0", optional = true }
parsers = { path = "../parsers", version = "0.0.0", optional = true }
structopt = { version = "0.3.25", optional = true }


# For `kernel-*` features
kernel-bash = { path = "../kernel-bash", version = "0.0.0", optional = true }
kernel-calc = { path = "../kernel-calc", version = "0.0.0", optional = true }
kernel-deno = { path = "../kernel-deno", version = "0.0.0", optional = true }
kernel-jupyter = { path = "../kernel-jupyter", version = "0.0.0", optional = true }
kernel-micro = { path = "../kernel-micro", version = "0.0.0", optional = true }
kernel-node = { path = "../kernel-node", version = "0.0.0", optional = true }
kernel-python = { path = "../kernel-python", version = "0.0.0", optional = true }
kernel-r = { path = "../kernel-r", version = "0.0.0", optional = true }
kernel-store = { path = "../kernel-store", version = "0.0.0", optional = true }
kernel-zsh = { path = "../kernel-zsh", version = "0.0.0", optional = true }
