[package]
name = "node-execute"
description = "Compile and execute Stencila document nodes"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
eyre = "0.6.6"
formats = { path = "../formats", version = "0.0.0" }
futures = "0.3.19"
graph = { path = "../graph", version = "0.0.0" }
graph-triples = { path = "../graph-triples", version = "0.0.0" }
kernels = { path = "../kernels", version = "0.0.0" }
node-address = { path = "../node-address", version = "0.0.0" }
node-dispatch = { path = "../node-dispatch", version = "0.0.0" }
node-patch = { path = "../node-patch", version = "0.0.0" }
node-pointer = { path = "../node-pointer", version = "0.0.0" }
parsers = { path = "../parsers", version = "0.0.0" }
path-utils = { path = "../path-utils", version = "0.0.0" }
serde = { version = "1.0.130", features = ["derive"] }
stencila-schema = { path = "../schema" }
tokio = { version = "1.13.0", features = ["macros"] }
tracing = "0.1.29"
uuids = { path = "../uuids", version = "0.0.0" }

[dev-dependencies]
codec = { path = "../codec", version = "0.0.0" }
codec-md = { path = "../codec-md", version = "0.0.0" }
node-patch = { path = "../node-patch", version = "0.0.0" }
serde_json = "1.0.75"
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
# Enable the parser and kernel for any languages used in tests
parsers = { path = "../parsers", version = "0.0.0", features = ["parser-calc", "parser-r", "parser-py"] }
kernels = { path = "../kernels", version = "0.0.0", features = ["kernel-store", "kernel-calc"] }
