[package]
name = "node-execute"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-cbor = { path = "../codec-cbor" }
codec-markdown-trait = { path = "../codec-markdown-trait" }
codecs = { path = "../codecs" }
common = { path = "../common" }
kernels = { path = "../kernels" }
parsers = { path = "../parsers" }
prompts = { path = "../prompts" }
schema = { path = "../schema" }
