[package]
name = "stencila-codec-email"
version = "0.0.0"
edition = "2024"

[dependencies]
mrml = "5.1"
serde_json = { workspace = true }
stencila-codec = { path = "../codec" }
stencila-codec-dom-trait = { path = "../codec-dom-trait" }
stencila-codec-text-trait = { path = "../codec-text-trait" }
stencila-convert = { path = "../convert" }
stencila-themes = { path = "../themes" }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
