[package]
name = "stencila-agents"
edition = "2024"
version.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
jsonschema = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stencila-models3 = { path = "../models3" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
