[package]
name = "stencila-codec-site"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
ignore = { workspace = true }
md-5 = "0.10"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
stencila-cloud = { path = "../cloud" }
stencila-codec = { path = "../codec" }
stencila-codec-dom = { path = "../codec-dom" }
stencila-codec-utils = { path = "../codec-utils" }
stencila-config = { path = "../config" }
stencila-dirs = { path = "../dirs" }
stencila-format = { path = "../format" }
stencila-node-media = { path = "../node-media" }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
