[package]
name = "codec-dom"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-dom-trait = { path = "../codec-dom-trait" }
codec-text-trait = { path = "../codec-text-trait" }
lightningcss = "1.0.0-alpha.61"
quick-xml = { workspace = true }

[lints]
workspace = true
