[package]
name = "stencila-codec-dom"
version = "0.0.0"
edition = "2024"

[dependencies]
itertools = { workspace = true }
lightningcss = { workspace = true }
quick-xml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stencila-codec = { path = "../codec" }
stencila-codec-dom-trait = { path = "../codec-dom-trait" }
stencila-codec-text-trait = { path = "../codec-text-trait" }
stencila-config = { path = "../config" }
stencila-node-media = { path = "../node-media" }
stencila-themes = { path = "../themes" }
stencila-version = { path = "../version" }
tokio = { workspace = true }

[lints]
workspace = true
