name: Assign project to all issues and pull requests

on:
  issues:
    types: [opened]
  pull_request:
    branches: '*'
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.2
        with:
          project: Stencila Roadmap
          column: Backlog
          repo-token: ${{ secrets.STENCILA_BOT_TOKEN }}
