[package]
name = "stencila-linter-harper"
version = "0.0.0"
edition = "2024"

[dependencies]
harper-core = { version = "1.4.1", features = ["concurrent"] }
itertools = { workspace = true }
stencila-linter = { path = "../linter" }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
