[package]
name = "stencila-dirs"
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
directories = { workspace = true }
eyre = { workspace = true }
smart-default = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
